#pragma once

#include "Kernel/Interface/IFileObject.h"

namespace Display
{
	namespace Interface
	{
#pragma region Block Type
		enum
		{
			BLOCKTYPE_DISPLAY = BLOCKTYPE_HYENGINE_NEXT,
			BLOCKTYPE_DISPLAY_OBJECT = BLOCKTYPE_DISPLAY + 10000,
			BLOCKTYPE_DISPLAY_OBJECT_MATERIAL,
			BLOCKTYPE_DISPLAY_OBJECT_COMPONENT,
			BLOCKTYPE_DISPLAY_OBJECT_COMPONENT2D,
			BLOCKTYPE_DISPLAY_OBJECT_COMPONENT3D,
			BLOCKTYPE_DISPLAY_OBJECT_DIMENSION,
			BLOCKTYPE_DISPLAY_OBJECT_TEXTURE,
			BLOCKTYPE_DISPLAY_OBJECT_VISION = BLOCKTYPE_DISPLAY_OBJECT + 1000,
			BLOCKTYPE_DISPLAY_OBJECT_VISION_DLIGHT,
			BLOCKTYPE_DISPLAY_OBJECT_VISION_DCAMERA,
			BLOCKTYPE_DISPLAY_OBJECT_GEOMETRY = BLOCKTYPE_DISPLAY_OBJECT + 2000,
			BLOCKTYPE_DISPLAY_OBJECT_GEOMETRY_SCENECOORDINATESYSTEM,
			BLOCKTYPE_DISPLAY_OBJECT_GEOMETRY_RULER,
			BLOCKTYPE_DISPLAY_OBJECT_GEOMETRY_POINT,
			BLOCKTYPE_DISPLAY_OBJECT_GEOMETRY_MULTILINE,
			BLOCKTYPE_DISPLAY_OBJECT_GEOMETRY_MULTILINES,
			BLOCKTYPE_DISPLAY_OBJECT_GEOMETRY_SLICEDPOLYGON,
			BLOCKTYPE_DISPLAY_OBJECT_GEOMETRY_SLICEDPOLYGONS,
			BLOCKTYPE_DISPLAY_OBJECT_GEOMETRY_LINE,
			BLOCKTYPE_DISPLAY_OBJECT_GEOMETRY_ARROW2D,
			BLOCKTYPE_DISPLAY_OBJECT_GEOMETRY_CIRCLE,
			BLOCKTYPE_DISPLAY_OBJECT_GEOMETRY_CYLINDER,
			BLOCKTYPE_DISPLAY_OBJECT_GEOMETRY_PIPE,
			BLOCKTYPE_DISPLAY_OBJECT_GEOMETRY_SPHERE,
			BLOCKTYPE_DISPLAY_OBJECT_GEOMETRY_GROUP,
			BLOCKTYPE_DISPLAY_OBJECT_GEOMETRY_COMBINATION,
			BLOCKTYPE_DISPLAY_OBJECT_GEOMETRY_COORDINATESYSTEM,
			BLOCKTYPE_DISPLAY_OBJECT_GEOMETRY_COORDINATESYSTEM2D,
			BLOCKTYPE_DISPLAY_OBJECT_GEOMETRY_BOUNDINGBOX,
			BLOCKTYPE_DISPLAY_OBJECT_GEOMETRY_RECTANGLE,
			BLOCKTYPE_DISPLAY_OBJECT_GEOMETRY_TRIANGLE,
			BLOCKTYPE_DISPLAY_OBJECT_GEOMETRY_HEXAHEDRON,
			BLOCKTYPE_DISPLAY_OBJECT_GEOMETRY_CUBE,
			BLOCKTYPE_DISPLAY_OBJECT_GEOMETRY_CLOUD,
			BLOCKTYPE_DISPLAY_OBJECT_GEOMETRY_POLYGON2D,
			BLOCKTYPE_DISPLAY_OBJECT_GEOMETRY_POLYGONS2D,
			BLOCKTYPE_DISPLAY_OBJECT_GEOMETRY_SLICEDPOLYGONS2D,
			BLOCKTYPE_DISPLAY_OBJECT_GEOMETRY_BITMAP,
			BLOCKTYPE_DISPLAY_OBJECT_GEOMETRY_GRID,
			BLOCKTYPE_DISPLAY_OBJECT_GEOMETRY_GRIDRULER,
			BLOCKTYPE_DISPLAY_OBJECT_GEOMETRY_GRIDDEEPENEXTAND,
			BLOCKTYPE_DISPLAY_OBJECT_GEOMETRY_PEDESTAL,
			BLOCKTYPE_DISPLAY_OBJECT_GEOMETRY_MODEL,
			BLOCKTYPE_DISPLAY_OBJECT_GEOMETRY_MANIPULATOR,
			BLOCKTYPE_DISPLAY_OBJECT_GEOMETRY_MESH = BLOCKTYPE_DISPLAY_OBJECT_GEOMETRY + 100,
			BLOCKTYPE_DISPLAY_OBJECT_GEOMETRY_MESH_POLYHEDRON,
			BLOCKTYPE_DISPLAY_OBJECT_GEOMETRY_PRINT = BLOCKTYPE_DISPLAY_OBJECT_GEOMETRY + 200,
			BLOCKTYPE_DISPLAY_OBJECT_GEOMETRY_PRINT_PRINTOBJECT,
			BLOCKTYPE_DISPLAY_OBJECT_GEOMETRY_PRINT_LASERPATHS,
			BLOCKTYPE_DISPLAY_OBJECT_GEOMETRY_PRINT_RECOATERDIRECTION2D,
			BLOCKTYPE_DISPLAY_OBJECT_GEOMETRY_PRINT_GASFLOWDIRECTION2D,
			BLOCKTYPE_DISPLAY_VIEW = BLOCKTYPE_DISPLAY + 20000,
			BLOCKTYPE_DISPLAY_VIEW_VIEWOBJECT,
			BLOCKTYPE_DISPLAY_VIEW_CONTROL = BLOCKTYPE_DISPLAY_VIEW + 1000,
			BLOCKTYPE_DISPLAY_VIEW_CONTROL_TEXT,
			BLOCKTYPE_HY3DRENDERINGENGINE_NEXT = BLOCKTYPE_HYENGINE_NEXT + 100000,
		};
#pragma endregion
	}
}