#pragma once
namespace Kernel
{
	namespace Slice
	{
		namespace Path
		{
			typedef enum _tagGeneratePathType
			{
				PATH_TYPE_MODEL_CONTOUR = 0x01,
				PATH_TYPE_MODEL_OUTERMOST_BORDER = 0x02,
				PATH_TYPE_MODEL_FOLLOWING_BORDER = 0x03,
				PATH_TYPE_MODEL_FILL_BORDER = 0x04,
				PATH_TYPE_MODEL_HATCH_VECTOR = 0x05,
				PATH_TYPE_MODEL_UP_SKIN = 0x06,
				PATH_TYPE_MODEL_IN_SKIN = 0x07,
				PATH_TYPE_MODEL_DOWN_SKIN = 0x08,
				PATH_TYPE_SUPPORT_CONTOUR = 0x21,
				PATH_TYPE_SUPPORT_OUTERMOST_BORDER = 0x22,
				PATH_TYPE_SUPPORT_FOLLOWING_BORDER = 0x23,
				PATH_TYPE_SUPPORT_FILL_BORDER = 0x24,
				PATH_TYPE_SUPPORT_HATCH_VECTOR = 0x25,
				PATH_TYPE_SUPPORT_UP_SKIN = 0x26,
				PATH_TYPE_SUPPORT_IN_SKIN = 0x27,
				PATH_TYPE_SUPPORT_DOWN_SKIN = 0x28,
			}EGeneratePathType;
		}
	}
}