#pragma once

#include "../Reshaper3DDefine.h"

namespace Kernel
{
	namespace File
	{
		RsDEFINE_CLASS(CFileReadObject);
		RsDEFINE_CLASS(CFileWriteObject);
	}

	namespace Util
	{
		RsDEFINE_CLASS(CProgress);
	}

	namespace Interface
	{
		using namespace Kernel::File;
		using namespace Kernel::Util;

#pragma region Block type
		enum
		{
			BLOCKTYPE_NONTYPE,
			// Kernel
			BLOCKTYPE_KERNEL = BLOCKTYPE_NONTYPE + 10000,
			// Kernel.Object
			BLOCKTYPE_KERNEL_OBJECT = BLOCKTYPE_KERNEL + 1000,
			BLOCKTYPE_KERNEL_OBJECT_BOUNDINGBOX2D,
			BLOCKTYPE_KERNEL_OBJECT_BOUNDINGBOX,
			BLOCKTYPE_KERNEL_OBJECT_DIMENSION2D,
			BLOCKTYPE_KERNEL_OBJECT_DIMENSION,
			BLOCKTYPE_KERNEL_OBJECT_RAY,
			BLOCKTYPE_KERNEL_OBJECT_PLATFORM,
			BLOCKTYPE_KERNEL_OBJECT_RESOLUTION,
			// Kernel.Object.Vision
			BLOCKTYPE_KERNEL_OBJECT_VISION = BLOCKTYPE_KERNEL_OBJECT + 100,
			BLOCKTYPE_KERNEL_OBJECT_VISION_CAMERA,
			// Kernel.Object.Geometry
			BLOCKTYPE_KERNEL_OBJECT_GEOMETRY = BLOCKTYPE_KERNEL_OBJECT + 200,
			BLOCKTYPE_KERNEL_OBJECT_GEOMETRY_POINTDOUBLE,
			BLOCKTYPE_KERNEL_OBJECT_GEOMETRY_POINT2DDOUBLE,
			BLOCKTYPE_KERNEL_OBJECT_GEOMETRY_POINTINT,
			BLOCKTYPE_KERNEL_OBJECT_GEOMETRY_POINT2INT,
			BLOCKTYPE_KERNEL_OBJECT_GEOMETRY_VERTEX,
			BLOCKTYPE_KERNEL_OBJECT_GEOMETRY_VERTEX2D,
			BLOCKTYPE_KERNEL_OBJECT_GEOMETRY_TRIANGLE,
			BLOCKTYPE_KERNEL_OBJECT_GEOMETRY_TRIANGLE2D,
			BLOCKTYPE_KERNEL_OBJECT_GEOMETRY_TRIANGLES,
			BLOCKTYPE_KERNEL_OBJECT_GEOMETRY_PLANE,
			BLOCKTYPE_KERNEL_OBJECT_GEOMETRY_MULTILINE,
			BLOCKTYPE_KERNEL_OBJECT_GEOMETRY_MULTILINE2D,
			BLOCKTYPE_KERNEL_OBJECT_GEOMETRY_MULTILINES,
			BLOCKTYPE_KERNEL_OBJECT_GEOMETRY_LINE,
			BLOCKTYPE_KERNEL_OBJECT_GEOMETRY_LINE2D,
			BLOCKTYPE_KERNEL_OBJECT_GEOMETRY_CROSS2D,
			BLOCKTYPE_KERNEL_OBJECT_GEOMETRY_CIRCLE,
			BLOCKTYPE_KERNEL_OBJECT_GEOMETRY_CIRCLE2D,
			BLOCKTYPE_KERNEL_OBJECT_GEOMETRY_ELLIPSE,
			BLOCKTYPE_KERNEL_OBJECT_GEOMETRY_ELLIPSE2D,
			BLOCKTYPE_KERNEL_OBJECT_GEOMETRY_CYLINDER,
			BLOCKTYPE_KERNEL_OBJECT_GEOMETRY_PIPE,
			BLOCKTYPE_KERNEL_OBJECT_GEOMETRY_SPHERE,
			BLOCKTYPE_KERNEL_OBJECT_GEOMETRY_FACE,
			BLOCKTYPE_KERNEL_OBJECT_GEOMETRY_EDGE,
			BLOCKTYPE_KERNEL_OBJECT_GEOMETRY_AXISSYSTEM,
			BLOCKTYPE_KERNEL_OBJECT_GEOMETRY_CUBE,
			BLOCKTYPE_KERNEL_OBJECT_GEOMETRY_RECTANGLE,
			BLOCKTYPE_KERNEL_OBJECT_GEOMETRY_RECTANGLE2D,
			BLOCKTYPE_KERNEL_OBJECT_GEOMETRY_CLOUD,
			BLOCKTYPE_KERNEL_OBJECT_GEOMETRY_CLOUD2D,
			BLOCKTYPE_KERNEL_OBJECT_GEOMETRY_SEGMENT,
			BLOCKTYPE_KERNEL_OBJECT_GEOMETRY_SEGMENT2D,
			BLOCKTYPE_KERNEL_OBJECT_GEOMETRY_HEXAHEDRON,
			BLOCKTYPE_KERNEL_OBJECT_GEOMETRY_POLYGON2D,
			BLOCKTYPE_KERNEL_OBJECT_GEOMETRY_POLYGONS2D,
			BLOCKTYPE_KERNEL_OBJECT_GEOMETRY_SPIRAL,
			BLOCKTYPE_KERNEL_OBJECT_GEOMETRY_PEDESTAL,
			// Kernel.Object.Geometry.Mesh
			BLOCKTYPE_KERNEL_OBJECT_GEOMETRY_MESH = BLOCKTYPE_KERNEL_OBJECT_GEOMETRY + 500,
			BLOCKTYPE_KERNEL_OBJECT_GEOMETRY_MESH_POLYHEDRON,
			// Kernel.Object.Pattern
			BLOCKTYPE_KERNEL_OBJECT_PATTERN = BLOCKTYPE_KERNEL_OBJECT + 700,
			BLOCKTYPE_KERNEL_OBJECT_PATTERN_LINE,
			BLOCKTYPE_KERNEL_OBJECT_PATTERN_RECTANGLE,
			BLOCKTYPE_KERNEL_OBJECT_PATTERN_TRIANGLE,
			BLOCKTYPE_KERNEL_OBJECT_PATTERN_CIRCLE,
			BLOCKTYPE_KERNEL_OBJECT_PATTERN_CLOUD,
			BLOCKTYPE_KERNEL_OBJECT_PATTERN_ELLIPSE,
			BLOCKTYPE_KERNEL_OBJECT_PATTERN_POLYGON,
			BLOCKTYPE_KERNEL_OBJECT_PATTERN_CROSS,
			BLOCKTYPE_KERNEL_OBJECT_PATTERN_PADDYFIELD,
			// Kernel.Object.Print
			BLOCKTYPE_KERNEL_OBJECT_PRINT = BLOCKTYPE_KERNEL_OBJECT + 800,
			BLOCKTYPE_KERNEL_OBJECT_PRINT_DEVICE,
			BLOCKTYPE_KERNEL_OBJECT_PRINT_MATERIAL,
			BLOCKTYPE_KERNEL_OBJECT_PRINT_SLICE,
			BLOCKTYPE_KERNEL_OBJECT_PRINT_PRINTCASE,
			// Kernel.Math
			BLOCKTYPE_KERNEL_MATH = BLOCKTYPE_KERNEL + 2000,
			BLOCKTYPE_KERNEL_MATH_EULER,
			BLOCKTYPE_KERNEL_MATH_QUATERNION,
			BLOCKTYPE_KERNEL_MATH_MATRIX2X2,
			BLOCKTYPE_KERNEL_MATH_MATRIX2X3,
			BLOCKTYPE_KERNEL_MATH_MATRIX3X3,
			BLOCKTYPE_KERNEL_MATH_MATRIX3X4,
			BLOCKTYPE_KERNEL_MATH_VECTOR,
			BLOCKTYPE_KERNEL_MATH_VECTOR2D,
			BLOCKTYPE_KERNEL_MATH_VELOCITY,
			BLOCKTYPE_KERNEL_MATH_MOVEMENTSPEED,
			BLOCKTYPE_KERNEL_MATH_PIDCONTROL,
			// Kernel.Math.Equation
			BLOCKTYPE_KERNEL_MATH_EQUATION = BLOCKTYPE_KERNEL_MATH + 100,
			BLOCKTYPE_KERNEL_MATH_EQUATION_PRIMARY,
			BLOCKTYPE_KERNEL_MATH_EQUATION_QUADRATIC,
			// Kernel.Math.Graph
			BLOCKTYPE_KERNEL_MATH_GRAPH = BLOCKTYPE_KERNEL_MATH + 200,
			// Kernel.Collection
			BLOCKTYPE_KERNEL_COLLECTION = BLOCKTYPE_KERNEL + 3000,
			BLOCKTYPE_KERNEL_COLLECTION_OBJECT = BLOCKTYPE_KERNEL_COLLECTION + 100,
			BLOCKTYPE_KERNEL_COLLECTION_OBJECT_MANAGEDOBJECT,
			// Kernel.Util
			BLOCKTYPE_KERNEL_UTIL = BLOCKTYPE_KERNEL + 4000,
			BLOCKTYPE_KERNEL_UTIL_VERSION,
			// Kernel.Slice
			BLOCKTYPE_KERNEL_SLICE = BLOCKTYPE_KERNEL + 5000,
			BLOCKTYPE_KERNEL_SLICE_SEGMENT2D,
			BLOCKTYPE_KERNEL_SLICE_MULTISEGMENTS2D,
			BLOCKTYPE_KERNEL_SLICE_SLICEDPOLYGON2D,
			BLOCKTYPE_KERNEL_SLICE_LASERPOLYGON,
			BLOCKTYPE_KERNEL_SLICE_SLADLP2SLICEDATA,
			BLOCKTYPE_KERNEL_SLICE_SLICEDPOLYGONS2D,
			BLOCKTYPE_KERNEL_SLICE_LASERPOLYGONS,
			BLOCKTYPE_KERNEL_SLICE_PATH = BLOCKTYPE_KERNEL_SLICE + 100,
			BLOCKTYPE_KERNEL_SLICE_PATH_PATTERN = BLOCKTYPE_KERNEL_SLICE + 200,
			BLOCKTYPE_KERNEL_SLICE_PATH_PATTERN_VECTOR,
			BLOCKTYPE_KERNEL_SLICE_PATH_PATTERN_ARC,
			BLOCKTYPE_KERNEL_SLICE_PATH_PATTERN_MODEL,
			BLOCKTYPE_KERNEL_SLICE_PATH_LPPATTERN = BLOCKTYPE_KERNEL_SLICE + 300,
			BLOCKTYPE_KERNEL_SLICE_PATH_LPRECTANGLE,
			BLOCKTYPE_KERNEL_SLICE_PATH_LPTRIANGLE,
			BLOCKTYPE_KERNEL_SLICE_PATH_LPCIRCLE,
			BLOCKTYPE_KERNEL_SLICE_PATH_LPCLOUD,
			BLOCKTYPE_KERNEL_SLICE_PATH_LPPADDYFIELD,
			BLOCKTYPE_KERNEL_SLICE_PATH_LPCALIBRATIONPATTERNFORMAX600,
			// Kernel.Draw
			BLOCKTYPE_KERNEL_DRAW = BLOCKTYPE_KERNEL + 6000,
			// Kernel.Position
			BLOCKTYPE_KERNEL_POSITION = BLOCKTYPE_KERNEL + 7000,
			// Kernel.Position.Window
			BLOCKTYPE_KERNEL_POSITION_WINDOW = BLOCKTYPE_KERNEL_POSITION + 100,
			BLOCKTYPE_KERNEL_POSITION_WINDOW_WINPOINTDOUBLE,
			// Kernel.Device
			BLOCKTYPE_KERNEL_DEVICE = BLOCKTYPE_KERNEL + 8000,
			// Kernel.Deivce.Print3D
			BLOCKTYPE_KERNEL_DEVICE_PRINT3D = BLOCKTYPE_KERNEL_DEVICE + 100,
			BLOCKTYPE_KERNEL_DEVICE_PRINT3D_LASERPROPERTY,
			BLOCKTYPE_KERNEL_DEVICE_PRINT3D_GALVANODELAYPROPERTY,
			BLOCKTYPE_KERNEL_DEVICE_PRINT3D_SKYWRITINGPROPERTY,
			BLOCKTYPE_KERNEL_DEVICE_PRINT3D_LASERVARIABLEPROPERTY,
			BLOCKTYPE_KERNEL_DEVICE_PRINT3D_LASEREXPANDERPROPERTY,
			BLOCKTYPE_KERNEL_DEVICE_PRINT3D_LASERPROPERTYELEMENT,
			BLOCKTYPE_KERNEL_DEVICE_PRINT3D_PARTPROPERTY,
			// Kernel.Device.Optic
			BLOCKTYPE_KERNEL_DEVICE_OPTICS = BLOCKTYPE_KERNEL_DEVICE + 200,
			BLOCKTYPE_KERNEL_DEVICE_OPTICS_POWERTABLE,
			// Kernel.Unit
			BLOCKTYPE_KERNEL_UNIT = BLOCKTYPE_KERNEL + 9000,
			BLOCKTYPE_KERNEL_UNIT_UNIT,
			BLOCKTYPE_KERNEL_UNIT_MOTORUNIT,
			// ThirdParty
			BLOCKTYPE_THIRDPARTY = BLOCKTYPE_NONTYPE + 90000,
			BLOCKTYPE_THIRDPARTY_OPTIMIZEDFACE,
			BLOCKTYPE_THIRDPARTY_OPTIMIZEDVERTEX,
			// Next HyEngine
			BLOCKTYPE_HYENGINE_NEXT = 100000,
			BLOCKTYPE_EOB = 999999,
		};
#pragma endregion

RsINTERFACE(IFileObject)
{
public:
	virtual const INT		ReadBin(CFileReadObject & file, CProgress * iProgress = NULL)		= 0;
	virtual const INT		SaveBin(CFileWriteObject & file, CProgress * iProgress = NULL)		= 0;
	virtual const UINT		GetBlockType() const												= 0;
};

	}
}