#include "Kernel/Reshaper3DDefine.h"
#include "Kernel/Reshaper3DErrorDefine.h"
#include "Kernel/Interface/IPrimitive.h"
#include "Kernel/Interface/IDataObject.h"
#include "Kernel/Interface/IEditedData.h"
#include "Kernel/Interface/IFileObject.h"
#include "Kernel/Interface/IDeviceObject.h"
#include "Kernel/Interface/IKeyObject.h"
#include "Kernel/Interface/IXMLObject.h"
#include "Kernel/Interface/IINIObject.h"
#include "Kernel/Interface/IPatternObject.h"
#include "Kernel/Interface/IEquation.h"
#include "Kernel/InterProcess/NamedPipe/CNamedPipeClient.h"
#include "Kernel/InterProcess/NamedPipe/CNamedPipeServerClient.h"
#include "Kernel/InterProcess/NamedPipe/CNamedPipeServer.h"
#include "Kernel/Primitive/Primitive.h"
#include "Kernel/Primitive/RectDouble.h"
#include "Kernel/String/HyString.h"
#include "Kernel/String/KeyString.h"
#include "Kernel/File/FileBase.h"
#include "Kernel/File/FileObject.h"
#include "Kernel/File/FileReadObject.h"
#include "Kernel/File/FileWriteObject.h"
#include "Kernel/File/MemoryStreamObject.h"
#include "Kernel/File/MemoryStreamRead.h"
#include "Kernel/File/MemoryStreamWrite.h"
#include "Kernel/File/FolderSystem.h"
#include "Kernel/File/Slice/CliFile.h"
#include "Kernel/File/Slice/SlcFile.h"
#include "Kernel/File/XML/XmlElement.h"
#include "Kernel/File/XML/XmlDocument.h"
#include "Kernel/File/XML/XmlObject.h"
#include "Kernel/File/LightXML/tinyxml2.h"
#include "Kernel/File/LightXML/TinyXmlHelper.h"
#include "Kernel/File/LightXML/LightXmlElement.h"
#include "Kernel/File/LightXML/LightXmlDocument.h"
#include "Kernel/File/LightXML/LightXmlObject.h"
#include "Kernel/File/SpreadSheet/CSpreadSheetCell.h"
#include "Kernel/File/SpreadSheet/CSpreadSheetRow.h"
#include "Kernel/File/SpreadSheet/CSpreadSheet.h"
#include "Kernel/File/SpreadSheet/CsvSpreadSheet.h"
#include "Kernel/Object/DataObject.h"
#include "Kernel/Unit/Unit.h"
#include "Kernel/Unit/MotorUnit.h"
#include "Kernel/File/Ini/IniObject.h"
#include "Kernel/Device/DeviceObject.h"
#include "Kernel/Draw/Color.h"
#include "Kernel/Draw/RawImage.h"
#include "Kernel/Draw/ExtBitmap.h"
#include "Kernel/Collection/Singleton.h"
#include "Kernel/Collection/TableArray.h"
#include "Kernel/Collection/TableList.h"
#include "Kernel/Collection/Object/ManagedObject.h"
#include "Kernel/Compression/Compression.h"
#include "Thirdparty/libzip/include/zip.h"
#include "Kernel/Compression/Archive/ArchiveManager.h"
#include "Kernel/Util/Util.h"
#include "Kernel/Util/Progress.h"
#include "Kernel/Util/Logger.h"
#include "Kernel/Util/Version.h"
#include "Kernel/Util/EditedDataModel.h"
#include "Kernel/Util/BitConverter.h"
#include "Kernel/Util/StockWatchTimer.h"
#include "Kernel/Util/StockWatchLogs.h"
#include "Kernel/Util/Thread/HealthCheck.h"
#include "Kernel/Util/Thread/Thread.h"
#include "Kernel/Util/Thread/MultiThread.h"
#include "Kernel/Util/Thread/MultiThreadTimer.h"
#include "Kernel/Object/Geometry/GeometryObject.h"
#include "Kernel/Math/Math.h"
#include "Kernel/Math/Velocity.h"
#include "Kernel/Math/MovementSpeed.h"
#include "Kernel/Math/Matrix2x2.h"
#include "Kernel/Math/Matrix3x3.h"
#include "Kernel/Object/Geometry/GPoint2DDouble.h"
#include "Kernel/Object/Geometry/GPointDouble.h"
#include "Kernel/Object/Geometry/GPoint2DInt.h"
#include "Kernel/Object/Geometry/GPointInt.h"
#include "Kernel/Math/Vector2D.h"
#include "Kernel/Math/Vector.h"
#include "Kernel/Math/Matrix2x3.h"
#include "Kernel/Math/Matrix3x4.h"
#include "Kernel/Math/Euler.h"
#include "Kernel/Math/Quaternion.h"
#include "Kernel/Math/ConvexHull.h"
#include "Kernel/Math/Equation/Equation.h"
#include "Kernel/Math/Equation/PrimaryEquation.h"
#include "Kernel/Math/Equation/QuadraticEquation.h"
#include "Kernel/Math/PIDControl.h"
#include "Kernel/Object/Dimension2D.h"
#include "Kernel/Object/Dimension.h"
#include "Kernel/Object/Platform.h"
#include "Kernel/Object/Resolution.h"
#include "Kernel/Object/BoundingBox2D.h"
#include "Kernel/Object/BoundingBox.h"
#include "Kernel/Object/Geometry/GSphere.h"
#include "Kernel/Object/Geometry/GRectangle2D.h"
#include "Kernel/Object/Geometry/GRectangle.h"
#include "Kernel/Object/Geometry/GHexahedron.h"
#include "Kernel/Object/Geometry/GCube.h"
#include "Kernel/Object/Geometry/GAxisSystem.h"
#include "Kernel/Object/Geometry/GPlane.h"
#include "Kernel/Object/Geometry/GVertex2D.h"
#include "Kernel/Object/Geometry/GVertex.h"
#include "Kernel/Object/Geometry/GPolygon2D.h"
#include "Kernel/Object/Geometry/GPolygons2D.h"
#include "Kernel/Object/Geometry/Mesh/GFace.h"
#include "Kernel/Object/Geometry/GMultiLine2D.h"
#include "Kernel/Object/Geometry/GMultiLine.h"
#include "Kernel/Object/Geometry/GMultiLines.h"
#include "Kernel/Object/Geometry/GLine2D.h"
#include "Kernel/Object/Geometry/GLine.h"
#include "Kernel/Object/Geometry/GCross2D.h"
#include "Kernel/Object/Geometry/GCircle2D.h"
#include "Kernel/Object/Geometry/GCircle.h"
#include "Kernel/Object/Geometry/GSpiral.h"
#include "Kernel/Object/Geometry/GEllipse2D.h"
#include "Kernel/Object/Geometry/GEllipse.h"
#include "Kernel/Object/Geometry/GCylinder.h"
#include "Kernel/Object/Geometry/GPipe.h"
#include "Kernel/Object/Geometry/GPedestal.h"
#include "Kernel/Object/Geometry/GTriangle2D.h"
#include "Kernel/Object/Geometry/GTriangle.h"
#include "Kernel/Object/Geometry/GCloud.h"
#include "Kernel/Object/Geometry/GCloud2D.h"
#include "Kernel/Object/Geometry/GSegment2D.h"
#include "Kernel/Object/Geometry/Mesh/GEdge.h"
#include "Kernel/Object/Geometry/Mesh/GPolyhedron.h"
#include "Kernel/Object/Vision/Camera.h"
#include "Kernel/Object/Geometry/Mesh/GOpenGLTable.h"
#include "Kernel/Object/Pattern/PatternObject.h"
#include "Kernel/Object/Pattern/PLine.h"
#include "Kernel/Object/Pattern/PRectangle.h"
#include "Kernel/Object/Pattern/PTriangle.h"
#include "Kernel/Object/Pattern/PCircle.h"
#include "Kernel/Object/Pattern/PCross.h"
#include "Kernel/Object/Pattern/PCloud.h"
#include "Kernel/Object/Pattern/PPaddyField.h"
#include "Kernel/Object/Print/PrintCase.h"
#include "Kernel/Object/Print/Device.h"
#include "Kernel/Object/Print/Material.h"
#include "Kernel/Object/Print/Slice.h"
#include "Kernel/Object/Print/BasePreference.h"
#include "Kernel/Object/Print/DevicePreference.h"
#include "Kernel/Object/Print/MaterialPreference.h"
#include "Kernel/Object/Print/SlicePreference.h"
#include "Kernel/Position/Window/WinPointDouble.h"
#include "ThirdParty/Polygon/clipper.hpp"
#include "Kernel/Slice/PolygonObject.h"
#include "ThirdParty/B9/Polygons.h"
#include "Kernel/Slice/PolygonSet.h"
#include "Kernel/Slice/Segment2D.h"
#include "Kernel/Slice/SlicedSegment.h"
#include "Kernel/Slice/MultiSegments2D.h"
#include "Kernel/Slice/SlicedPolygon.h"
#include "Kernel/Slice/SlicedPolygons.h"
#include "Kernel/Slice/SlicedPolygon2D.h"
#include "Kernel/Slice/PolygonLayers.h"
#include "Kernel/Slice/SlicedPolygons2D.h"
#include "Kernel/Slice/SliceFunctions.h"

using namespace Kernel;
using namespace Kernel::Primitive;
using namespace Kernel::Draw;
using namespace Kernel::Collection;
using namespace Kernel::Collection::Object;
using namespace Kernel::Math;
using namespace Kernel::Device;
using namespace Kernel::Object;
using namespace Kernel::Object::Geometry;
using namespace Kernel::Object::Vision;
using namespace Kernel::Object::Geometry::Mesh;
using namespace Kernel::Object::Pattern;
using namespace Kernel::Object::Print;
using namespace Kernel::Position;
using namespace Kernel::Position::Window;
using namespace Kernel::Compression;
using namespace Kernel::Compression::Archive;
using namespace Kernel::Util;
using namespace Kernel::Util::Thread;
using namespace Kernel::String;
using namespace Kernel::File;
using namespace Kernel::File::Slice;
using namespace Kernel::File::XML;
using namespace Kernel::File::SpreadSheet;
using namespace tinyxml2;
using namespace Kernel::File::LightXML;
using namespace Kernel::File::INI;
using namespace Kernel::Slice;
using namespace Kernel::Slice::File;
using namespace Kernel::Unit;
using namespace Kernel::InterProcess::NamedPipe;

#define	BEGIN_HYENGINE()		\
	CFileBase::Initialize();